name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    if: ${{ github.repository == 'capytal/www' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_DEPLOYMENT_ENV: Production
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ SECRETS.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ SECRETS.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: true
